### ISSUE TITLE
Display Issues with Untitled Notes

### ISSUE THREAD

**Issue by 3y3** [diplodoc-platform/transform#454]
Proof:

![image](https://github.com/diplodoc-platform/transform/assets/3931155/d480bf2c-2c10-45cc-9ac7-04c417ef2722)

**Comment by martyanovandrey** [comment]
### Problem
When a note lacks a title, the styles are poorly displayed due to the creation of an empty `<p>` element. This affects the layout and visual consistency, causing unnecessary space or misalignment.

### Solution
Modify the logic to prevent the creation of the `<p>` element when the title is empty. Ensure that the icon remains visible and properly aligned even without a title.

### Tasks
1. Identify Logic: Locate where the `<p>` element for the title is generated.
2. Adjust Creation: Implement a conditional that bypasses the creation of the <p> element if the title is empty.
3. Testing: Verify the display of notes with and without titles to ensure proper styling and icon alignment.
4. Review Icon Styling: Make sure the icon remains properly styled and positioned in the absence of a title.

Where is the code that needs to be corrected located:
js
https://github.com/diplodoc-platform/transform/tree/master/src/transform/plugins/notes

styles
https://github.com/diplodoc-platform/transform/blob/master/src/scss/_note.scss

**Comment by obenjiro** [comment]
@3y3 fixed it in https://github.com/diplodoc-platform/transform/pull/554 Could you kindly review this PR?
